### ISSUE TITLE
How to deal with exceptional cases?

### ISSUE THREAD

**Issue by bangerth** [paddywball/BDD21#10]
You have this function:
```
    def find_solidus_adiabat_intersection(self, Tp):

        """
        Returns intersection of the solidus and the adiabat for a given potential
        temperature.
        Note: Since the quadratic function is used for the solidus has a turning point
        around 12 GPa, 2000 oC, Tp
        """

        # define function for use in fsolve.
        #   - reads P, T, Tp, returns array with results from adiabat and solidus.
        #   - aims to find P and T which give [T - func(P, Tp) = 0] for both.
        def f(PT, Tp):
            P, T = PT
            z = np.array( [ T - self.calc_adiabat(P, Tp),
                            T - (self.calc_solidus(P)) ] )
            return z

        # try fsolve. if failing return nans.
        try:
            P_intercept, T_intercept = fsolve(f, [0., Tp], args=Tp)
        except RuntimeWarning:
            P_intercept = np.nan
            T_intercept = np.nan

        return P_intercept, T_intercept
```

First, it would be useful to document that the function might return `nan`s -- just like you do in the in-function commentary.

The bigger question is what should callers do if `nan` is returned? Any follow-up computations become meaningless in that case. I *think* that you are not actually doing any follow-up computations, but just stick the results into a table, but it would be useful to reason whether that case *should* happen at all. If you can't think of a reason why a root can ever not be found, then it would be more appropriate to just abort the program.

**Comment by paddywball** [comment]
This function I lifted from another one of my scripts. In this case, because we are only looking at particles where melting has occurred, this function will never return a nan

**Comment by paddywball** [comment]
I left the nan bit in as a fail safe, but if the script is working correctly it should never be necessary.
