### ISSUE TITLE
Use consistent naming scheme

### ISSUE THREAD

**Issue by bangerth** [paddywball/BDD21#11]
You have different ways of naming functions:
```
  calc_Dn_Ball
  fun_D_n
  dcs_dX
  melt_comp_Ball
  Ball_Fluidity
```
It is often useful to come up with a consistent naming scheme. For example:
* `get_*`: Return a member variable's value, or compute something based on member variables alone
* `compute_*`/`comp_*`: Compute something based on arguments and, possibly, the values of member variables
* `write_*`: obvious

The point is that functions *do* something, and so they should contain a *verb* that indicates what it is they do. The first function in my list above has that, the others do not. The second and third could pass (though using `D_n` and `Dn` is inconsistent) because they evaluate functions with names that a user would probably recognize. I would drop the `fun_` prefix, though, since you're not using it in `dcx_dX` or `calc_Dn_Ball` either). The last two functions do something, but it's unclear what that is.

**Comment by paddywball** [comment]
I agree this would be a lot clearer, I will change the code accordingly.
