### ISSUE TITLE
Use all features of scipy.

### ISSUE THREAD

**Issue by marcfehling** [paddywball/BDD21#3]
I would like to encourage you to use the [`scipy.constants`](https://docs.scipy.org/doc/scipy/reference/constants.html) package for universal constants rather than defining them yourself, e.g., gravitation constant, gas constant, Avogadro's number...

---

https://github.com/paddywball/BDD21/blob/0e181d464dd17c11231d5f8b846f876124df018b/Fluidity_Chem_Mods.py#L150
```
self.N = scipy.constants.Avogadro
```

**Comment by marcfehling** [comment]
You can also use `scipy` to [convert units](https://docs.scipy.org/doc/scipy/reference/generated/scipy.constants.convert_temperature.html#scipy.constants.convert_temperature). This makes your code easier to read in my opinion.

---

https://github.com/paddywball/BDD21/blob/0e181d464dd17c11231d5f8b846f876124df018b/Fluidity_Chem_Mods.py#L261
```
(Tp+273.15) -> scipy.constants.convert_temperature(Tp, 'Celsius', 'Kelvin')
P * 1e9     -> P * scipy.constants.giga 
```

**Comment by paddywball** [comment]
I have made these changes and removed certain parameters from the class and I just define them in this way throughout the script.
