### ISSUE TITLE
Pick more descriptive function name

### ISSUE THREAD

**Issue by bangerth** [paddywball/BDD21#8]
You've got this function:
```
def add_string(a):
    # Concatenate all elements in two columns in array together.
    # Add in trailing zeros to make unique identifier.   
    return float(str(int(a[0])).zfill(3) + str(int(a[1])).zfill(8))
```
Name and documentation don't match: the function name says nothing about columns, and nothing is actually *added to*, just concatenated.

**Comment by paddywball** [comment]
I have changed it to 

def make_ID_number(a):
    # Concatenate all elements in two columns in array together.
    # Concatenate trailing zeros to make unique identifier.   
    return float(str(int(a[0])).zfill(3) + str(int(a[1])).zfill(8))
