### ISSUE TITLE
Introduce year_in_seconds

### ISSUE THREAD

**Issue by bangerth** [paddywball/BDD21#9]
I found this line:
```
partKatzFrate = partKatzFrate_proc[mask] * 3.1536e+13
```
The number is probably unfamiliar to most people. This would be easier to read if you had a line somewhere of the form
```
year_in_seconds = 60*60*24*365.2425
```
and then wrote the above as
```
partKatzFrate = partKatzFrate_proc[mask] * year_in_seconds * 1e6  # rate per million years
```

**Comment by bangerth** [comment]
Separately, the number you have here has an unclear origin to me. I had to look this up, and found that one can define the year in many different ways :-) But the correct number seems to be somewhere around 31556925.216 seconds, which is a smidgen larger than what you have -- it probably makes no difference for what you are doing, but illustrates the usefulness of defining things in one place with a symbolic name.

**Comment by bangerth** [comment]
I correct myself -- your number is based on the Gregorian year, which is exactly the `365.2425 * 24 * 60 * 60` I used above.

**Comment by paddywball** [comment]
Yeah, I am happy to make this change (and similar changes)

**Comment by marcfehling** [comment]
[`scipy.constants`](https://docs.scipy.org/doc/scipy/reference/constants.html) can do that for you, too.
```
scipy.constants.year        -- one year (365 days) in seconds
scipy.constants.Julian_year -- one year (365.25 days) in seconds
```
Ha! But it lacks the Gregorian year.
